# Generated by Django 5.0.7 on 2026-08-25

import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('novostroyka', 'Novostroyka'), ('vtorichka', 'Vtorichka')], max_length=20)),
                ('deal_type', models.CharField(choices=[('sale', 'Prodaja'), ('rent', 'Arenda')], max_length=10)),
                ('rooms_count', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('total_floors', models.PositiveSmallIntegerField()),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_per_sqm', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_listings', to='accounts.user')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.district')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.propertyowner')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=listings.models.listing_image_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
