# Generated by Django 5.1.4 on 2026-08-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_seed_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.TextField(blank=True, help_text="To'liq manzil"),
        ),
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.TextField(blank=True, help_text="Qo'shimcha sharoitlar (lift, internet, etc.)"),
        ),
        migrations.AddField(
            model_name='listing',
            name='nearby',
            field=models.TextField(blank=True, help_text='Yaqinidagi obyektlar'),
        ),
    ]
