# Generated by Django 5.0.7 on 2026-09-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_address_listing_amenities_listing_nearby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='deal_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('novostroyka', 'Новостройка'), ('vtorichka', 'Вторичка')], max_length=20),
        ),
    ]
